import { Sora } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/global/Header";

const sora = Sora({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});


export const metadata = {
  title: "Docifyy",
  description: "Generated by Chungsiang Roeurn",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="{sora.variable}">
      <body>
        {children}
      </body>
    </html >
  );
}
